version: "3.3"

services:
  pg:
    image: postgres:11.5-alpine
    container_name: pg-database
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - redePostgres

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  #     PGADMIN_DEFAULT_PASSWORD: "admin"
  #   ports:
  #     - "8888:80"
  #   depends_on:
  #     - pg
  #   networks:
  #     - redePostgres

  server:
    image: joaomede/nodejs12prod:1.0
    container_name: "server-api-doc"
    ports:
      - 8080:80
    depends_on:
      - pg
    links:
      - pg
    environment:
      HOSTDB: pg
    env_file:
      - .env
    command: yarn dev
    volumes:
      - .:/usr/src/app
      - /etc/letsencrypt:/etc/letsencrypt
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - redePostgres

networks:
  redePostgres:
    driver: bridge
