version: "3.3"

services:
  pg:
    image: postgres:11.5-alpine
    container_name: pg-database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: banco
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - apidoc-network

  server:
    image: joaomede/apidoc:v1.4.1
    container_name: "server-api-doc"
    depends_on:
      - pg
    links:
      - pg
    environment:
      HOSTDB: pg
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: banco
      NODE_ENV: dev
      HOSTSMTP: smtp.gmail.com
      PASSWORDSMTP: 123
      SECRET: teste
    ports:
      - 8080:80
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - apidoc-network

networks:
  apidoc-network:
    driver: bridge
