name: main
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Api Rest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm build
